In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
#1 image per interation
#224 by 224 pixels
#3 channels, 1 for each RPS option colour

while True: 
    ret, frame = cap.read()
    #turning image into a matrix of numbers for RPS
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.putText(frame, "Rock, Paper, Scissors. Play Game?", (30, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 0), 3)
    if prediction[0][0] > 0.5:
        #nested list
        print("Rock")
    elif prediction[0][1] > 0.5:
        print ("Paper")
    elif prediction[0][2] > 0.5:
        print("Scissors")
    else: 
        print ("Nothing")
    cv2.imshow('frame', frame)
    #shows what webcam is capturing
    
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 1s 677ms/step
Scissors
[[0.15067184 0.00108625 0.8453956  0.00284625]]
1/1 [==============================] - 0s 23ms/step
Rock
[[9.6440005e-01 5.4525557e-05 3.5415366e-02 1.3016624e-04]]
1/1 [==============================] - 0s 24ms/step
Rock
[[9.7915053e-01 1.3489756e-04 2.0615790e-02 9.8763783e-05]]
1/1 [==============================] - 0s 23ms/step
Rock
[[9.8158908e-01 1.8987739e-04 1.8151572e-02 6.9569243e-05]]
1/1 [==============================] - 0s 23ms/step
Rock
[[9.8158908e-01 1.8987739e-04 1.8151572e-02 6.9569243e-05]]
1/1 [==============================] - 0s 22ms/step
Rock
[[9.6380943e-01 2.0813795e-04 3.5682697e-02 2.9974725e-04]]
1/1 [==============================] - 0s 23ms/step
Rock
[[9.82486248e-01 1.21811710e-04 1.72739979e-02 1.17901036e-04]]
1/1 [==============================] - 0s 23ms/step
Rock
[[9.82486248e-01 1.21811710e-04 1.72739979e-02 1.17901036e-04]]
1/1 [==============================] - 0s 24ms/step
Rock
[[9.55

In [ ]:
def get_winner(self):
    if self.user_choice == self.computer_choice:
        print("Tie")
    
    while self.user_choice == self.prediction[0][0]:
        if self.computer_choice == self.prediction[0][2]:
            print("User wins!")
        if self.computer_choice == self.prediction[0][1]:
            print ("Computer wins!")
    
    while self.user_choice == self.prediction[0][1]:
        if self.computer_choice == self.prediction[0][0]:
            print("User wins!")
        if self.computer_choice == self.prediction[0][2]:
            print ("Computer wins!")
    
    while self.user_option == self.prediction[0][2]:
        if self.computer_option == self.prediction[0][1]:
            print("User wins!")
        if self.computer_option == self.prediction[0][0]:
            print ("Computer wins!")

In [ ]:
def get_computer_choice(self, computer_choice, option_list):
    self.option_list = ["rock", "paper", "scissors"]
    computer_choice = random.choice(option_list)
    return computer_choice

def get_user_choice(self, user_choice):
    self.user_choice = input
    return user_choice